### ISSUE TITLE
Cannot access full jq error details

### ISSUE THREAD

**Issue by mandatoryprogrammer** [fiatjaf/jq-web#13]
Hello,

I recently took a look at this library and it appears that the error details are stripped a bit before being passed to the `Promise.reject`?

The error I get is a string of `Error: 1 compile error` when the error I want is the verbose error that `jq` would normally provide:
```
jq: error: syntax error, unexpected '$', expecting IDENT or __loc__ (Unix shell quoting issues?) at <top-level>, line 1:
$$ 
jq: 1 compile error
```

I can see that the full error is actually returned by the WASM:
<img width="1441" alt="Screen Shot 2019-11-02 at 5 54 44 PM" src="https://user-images.githubusercontent.com/5349141/68078753-09a35200-fd9a-11e9-8113-5df8c67b7f5d.png">

But it appears its stripped in the source maybe here?: https://github.com/fiatjaf/jq-web/blob/a9b0a2d203d016de745829b933f6f5d4dbeb0097/post.js#L30

With the error being stripped down it makes it pretty painful to debug issues with the JQ syntax. In my specific case users are providing them so I'd like to give somewhat helpful feedback about what they can change instead of a vague `compile error` string.

I think fixing this should be easy? Just don't split on the `:`? Let me know if I'm reading this correctly.

**Comment by fiatjaf** [comment]
I've tried to be fancy here: you can access the full output at `err.stack`. `err.message` will continue as the same uncomplete unhelpful error message thing. Hopefully this solves the issue for you.

**Comment by mandatoryprogrammer** [comment]
Sick, thanks! Would you mind pushing the update to `npm`?

**Comment by fiatjaf** [comment]
Ok, forgot about that.
