### ISSUE TITLE
todate doesn't work in chrome extension.

### ISSUE THREAD

**Issue by zhangweis** [fiatjaf/jq-web#17]
jq.json({},'now|todate')
This will throw exception "jq: error (at <stdin>:0): strftime/1 requires parsed datetime inputs"

**Comment by zhangweis** [comment]
I've tried in other environments like node and chrome web and it works there. It throws exception only when in chrome extension.

**Comment by fiatjaf** [comment]
The issue is more likely related to `now`. Can you run just `now`?

That function somehow fetches the date from the system and Emscripten abstracts that somehow so the date is fetched (probably) from JavaScript's `new Date()`. Can you run `new Date()` in that same context?

**Comment by zhangweis** [comment]
Forget it. It seems like I have to use parentheses to wrap it like (now|todate) in chrome extension code.

**Comment by zhangweis** [comment]
Actually I'm using something like ".date=now|todate", and it will fetch the whole object to todate instead of the result of now. It's fixed by simply adding parentheses like ".date=(now|todate)".

**Comment by fiatjaf** [comment]
Great, thank you for posting the fix here. These `jq` parenthesis issues are likely to bite many people in the past and future.
