### ISSUE TITLE
Failure to include jq files

### ISSUE THREAD

**Issue by angeloaltamiranom** [fiatjaf/jq-web#23]
Hello, I want to use `jq-web` with my own `.jq` files where I have defined functions. Is this possible? I have tried using:

```
include "migrations" {search: "$ORIGIN/../../src/migrate/internal"}; [usage of functions inside .jq]
```
But it fails to find the files I need.

**Comment by fiatjaf** [comment]
It's not possible, but you can still manually include these files by reading their content and passing them to jq-web.
