### ISSUE TITLE
jq-web no longer builds with modern emscripten.

### ISSUE THREAD

**Issue by FGasper** [fiatjaf/jq-web#33]
Two changes have happened:
- `MODULARIZE_INSTANCE` is removed.
- The default output format is now a linked executable, not an object file.

**Comment by FGasper** [comment]
(I’ll have a PR shortly.)

**Comment by fiatjaf** [comment]
There are other libraries out there that expose jq over wasm. Maybe I should archive this repo and point people to others? I never tried any though.

**Comment by FGasper** [comment]
@fiatjaf I looked at a few:
- NPM [jq-wasm](https://www.npmjs.com/package/jq-wasm): Seems to be a fork of yours, but the maintainer doesn’t provide code.
- Another [jq-wasm](https://github.com/pboutes/jq-wasm) seems meant more as a freestanding web app than as a library.
- Yet another [jq-wasm](https://github.com/paolosimone/jq-wasm) is an update of yours, but it doesn’t seem to address some of the issues (e.g., memory leak) that I found.

Yours is the only one that I can find on GitHub _and_ on NPM.

**Comment by FGasper** [comment]
Fixed with latest PR merge.
